[package]
name = "color-lib"
version = "0.1.0"
edition = "2021"
description = "A library for implementing colors and converting between different representations. Includes a library easy access default colors."
license = "MIT OR Apache-2.0"

[dependencies]
